# Generated by Django 5.1.6 on 2026-04-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingArtist',
            fields=[
            ],
            options={
                'verbose_name': 'Onay Bekleyen Sanatçı',
                'verbose_name_plural': 'Onay Bekleyen Sanatçılar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
