services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: musiki
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d musiki"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./musiki_backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      POSTGRES_HOST: db
      POSTGRES_DB: musiki
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      USE_NGINX_ACCEL: "false"
    ports:
      - "8000:8000"
    volumes:
      - ./musiki_backend:/app
      - static_volume:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery:
    build:
      context: ./musiki_backend
    command: celery -A config worker -l info --without-gossip --without-mingle
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      POSTGRES_HOST: db
      POSTGRES_DB: musiki
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ./musiki_backend:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./musiki_backend/media:/media
      - static_volume:/staticfiles
    depends_on:
      backend:
        condition: service_started

volumes:
  postgres_data:
  static_volume:
