# Generated by Django 5.1.6 on 2026-04-06 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listenhistory',
            name='duration_ms',
            field=models.PositiveIntegerField(default=0, help_text='Kullanıcının bu oturumda dinlediği süre (milisaniye)'),
        ),
        migrations.AddIndex(
            model_name='listenhistory',
            index=models.Index(fields=['user', 'listened_at'], name='idx_user_listened'),
        ),
    ]
