# Generated by Django 5.1.6 on 2026-04-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_playlist_albumlike_artistfollow_playlistitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
